[FIX] refacto 2 cicd

diff --git a/.github/workflows/check-and-release.yml b/.github/workflows/check-and-release.yml
--- a/.github/workflows/check-and-release.yml
+++ b/.github/workflows/check-and-release.yml
@@ -1,8 +1,9 @@
-name: Build and Deploy Harmonia
+name: Harmonia CI/CD
 
 on:
   push:
     branches:
+      - dev
       - main
 
 jobs:
@@ -10,7 +11,8 @@ jobs:
     runs-on: windows-latest
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout
+        uses: actions/checkout@v4
         with:
           submodules: recursive
 
@@ -19,6 +21,15 @@ jobs:
 
       - name: Build
         run: cmake --build build --config Release
+
+      - name: Check EXE
+        run: |
+          if (!(Test-Path "build/HarmoniaPlugin_artefacts/Release/Standalone/HarmoniaPlugin.exe")) {
+            Write-Error "EXE not found"
+            exit 1
+          } else {
+            Write-Host "EXE found"
+          }
 
       - name: Check VST3
         run: |
@@ -29,20 +40,35 @@ jobs:
             Write-Host "VST3 found"
           }
 
+      - name: Upload EXE Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: Harmonia-EXE
+          path: build/HarmoniaPlugin_artefacts/Release/Standalone/HarmoniaPlugin.exe
+
+      - name: Upload VST3 Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: Harmonia-VST3
+          path: build/HarmoniaPlugin_artefacts/Release/VST3/HarmoniaPlugin.vst3
+
       - name: Create Release Folder
+        if: github.ref == 'refs/heads/main'
         run: mkdir release
 
       - name: Zip VST3
+        if: github.ref == 'refs/heads/main'
         run: |
           Compress-Archive `
             -Path "build/HarmoniaPlugin_artefacts/Release/VST3/HarmoniaPlugin.vst3" `
             -DestinationPath "release/Harmonia.zip"
 
       - name: Upload ZIP to VPS
+        if: github.ref == 'refs/heads/main'
         uses: appleboy/scp-action@v0.1.7
         with:
           host: ${{ secrets.VPS_HOST }}
           username: ${{ secrets.VPS_USERNAME }}
           key: ${{ secrets.VPS_SSH_KEY }}
           source: "release/Harmonia.zip"
-          target: "/var/www/harmonia-downloads"
+          target: "/var/www/harmonia-downloads/release"
