[FIX] deploy vps vst3

diff --git a/.github/workflows/test-standalone.yml b/.github/workflows/test-standalone.yml
--- a/.github/workflows/test-standalone.yml
+++ b/.github/workflows/test-standalone.yml
@@ -3,7 +3,7 @@ name: Build Windows and Test Standalone/VST3 (JUCE)
 on:
   push:
     branches:
-      - main
+      - dev
 
 jobs:
   build:
@@ -20,7 +20,16 @@ jobs:
       - name: Build
         run: cmake --build build --config Release
 
-      - name: Check VST3
+      - name: Check EXE
+        run: |
+          if (!(Test-Path "build/HarmoniaPlugin_artefacts/Release/Standalone/HarmoniaPlugin.exe")) {
+            Write-Error "EXE not found"
+            exit 1
+          } else {
+            Write-Host "EXE found"
+          }
+
+      - name: Check VST3 created by Plugin
         run: |
           if (!(Test-Path "build/HarmoniaPlugin_artefacts/Release/VST3/HarmoniaPlugin.vst3")) {
             Write-Error "VST3 not found"
@@ -29,20 +38,14 @@ jobs:
             Write-Host "VST3 found"
           }
 
-      - name: Create Release Folder
-        run: mkdir release
-
-      - name: Zip VST3
-        run: |
-          Compress-Archive `
-            -Path "build/HarmoniaPlugin_artefacts/Release/VST3/HarmoniaPlugin.vst3" `
-            -DestinationPath "release/Harmonia.zip"
-
-      - name: Upload ZIP to VPS
-        uses: appleboy/scp-action@v0.1.7
+      - name: Upload EXE
+        uses: actions/upload-artifact@v4
         with:
-          host: ${{ secrets.VPS_HOST }}
-          username: ${{ secrets.VPS_USERNAME }}
-          key: ${{ secrets.VPS_SSH_KEY }}
-          source: "release/Harmonia.zip"
-          target: "/var/www/harmonia-downloads"
+          name: Harmonia-EXE
+          path: build/HarmoniaPlugin_artefacts/Release/Standalone/HarmoniaPlugin.exe
+
+      - name: Upload VST3
+        uses: actions/upload-artifact@v4
+        with:
+          name: Harmonia-VST3
+          path: build/HarmoniaPlugin_artefacts/Release/VST3/HarmoniaPlugin.vst3
